### ISSUE TITLE
Some 12x12 glyphs leave their cell

### ISSUE THREAD

**Issue by exaskye** [byackley/pixelfonts#1]
Some of the 12x12 glyphs leave their cell in the atlas, resulting in random dots when drawing text with the 12x12 font.

![screenshot](https://user-images.githubusercontent.com/6185037/47115504-46171500-d24e-11e8-9e29-2221745262a0.png)

![screenshot](https://user-images.githubusercontent.com/6185037/47115530-58914e80-d24e-11e8-8fbb-8306d40976dc.png)

Thanks for all your work on these fonts, especially the emoji support in the 8x12. I don't know of any other pixel font projects attempting to tackle emoji.

**Comment by byackley** [comment]
Sorry for the delay on getting back to this, but this turned out to be a simple off-by-one error (the entire 00.png sheet was shifted one pixel too high). The next version will fix this.

**Comment by byackley** [comment]
Should be fixed now (and please let me know if there are any other issues).
